### PR TITLE
Fixed issue #10

### PR DESCRIPTION
**Pull request by M1hacka**
Fixing issue https://github.com/idlesign/pysyge/issues/10

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you.

I would like to ask you to run tests both on Py2 and 3, cause  this fix seems not being backward compatible. Despite https://idlesign.github.io/lbc/ we need to work on 2 till 2020.

We'd probably need to setup Travis to automatically run testsuite on pull requests. You may address it inthis very pull request if you will.

**Comment by M1hacka** [comment]
I've tested this commit both on python 3.7 and 2.7.
On 2.7 test `tests.test_module.TestGeoLocatorFileModeCheck.test_location_detailed` fails. But I'm not sure why, as it failed before my changes too.

**Comment by M1hacka** [comment]
Fixed failing test (direct `isinstance(..., str)` instead of `isinstance(..., string_type)`

**Comment by idlesign** [comment]
Thank you. Merged.

**Comment by M1hacka** [comment]
Hi. When release can be expected?

**Comment by idlesign** [comment]
Let's target this week. 
But maybe even today.

**Comment by M1hacka** [comment]
Thanks

**Comment by idlesign** [comment]
Made that. 
1.0.1 on PyPI.

**Pull request merged**
